services:
  qat_computer:
    container_name: ${CONTAINER_NAME:-qatcomputer}
    image: ${CONTAINER_NAME:-qatcomputer}:latest
    privileged: true
    cgroup: host
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        FULL: ${FULL:-false}
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "./qat_computer/resources/conf:/etc/qat-computer/conf:rw"
      - "./qat_computer/resources/compute:/etc/qat-computer/compute:rw"