name: Golang tests

on:
  pull_request:
  workflow_dispatch:

env:
  GO_DIR: src
  GO_VERSION: 1.19

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${GO_VERSION}
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: fmt
        run: |
          cd "${GO_DIR}"
          check=$(go fmt)
          if [["${check}" -ne ""]]; then
            exit 1
          fi

  unittests:
    name: go_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: run tests
        run: |
          cd "${GO_DIR}"
          go test ./... -covermode=count -coverprofile ./coverage.out
      - name: coverage
        run: |
          cd "${GO_DIR}"
          total_cov=$(go tool cover -func ./coverage.out | grep total |  grep -Eo '[0-9]+\.[0-9]+')
          if [[ "$total_cov" < 80.0 ]]; then
            echo "not enought tests"
            echo "::warning title=not enought tests::${total_cov}%"
            #exit 1
          fi

  configlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ${GO_DIR}/conf
          config_data: "{extends: default, rules: {line-length: disable}}"