name: Python tests

on:
  pull_request:
  workflow_dispatch:

env:
  PY_VERSION: 3.9
  IMAGE_NAME: "qatcomputer"

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PY_VERSION }}
      - uses: actions/checkout@v3
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run lint check
        run: tox -elint
      - name: Run black check
        run: tox -eblack

  end2end:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PY_VERSION }}
      - uses: actions/checkout@v3
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Build image
        run: |
          docker build . --build-arg FULL=false --file docker/Dockerfile --tag ${{ env.IMAGE_NAME }}:latest
      - name: Test using tox environment
        run: |
          pver=${{ env.PY_VERSION }}
          tox -epy${pver/./}